package co.com.virtualAsisIA.models;
// Generated 20/11/2015 04:16:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Accion generated by hbm2java
 */
@Entity
@Table(name="accion"
    ,schema="public"
)
public class Accion  implements java.io.Serializable {


     private int id;
     private String accion;
     private Set clasificacionPreguntas = new HashSet(0);
     private Set unificacionAccions = new HashSet(0);

    public Accion() {
    }

	
    public Accion(int id) {
        this.id = id;
    }
    public Accion(int id, String accion, Set clasificacionPreguntas, Set unificacionAccions) {
       this.id = id;
       this.accion = accion;
       this.clasificacionPreguntas = clasificacionPreguntas;
       this.unificacionAccions = unificacionAccions;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="accion", length=50)
    public String getAccion() {
        return this.accion;
    }
    
    public void setAccion(String accion) {
        this.accion = accion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="accion")
    public Set getClasificacionPreguntas() {
        return this.clasificacionPreguntas;
    }
    
    public void setClasificacionPreguntas(Set clasificacionPreguntas) {
        this.clasificacionPreguntas = clasificacionPreguntas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="accion")
    public Set getUnificacionAccions() {
        return this.unificacionAccions;
    }
    
    public void setUnificacionAccions(Set unificacionAccions) {
        this.unificacionAccions = unificacionAccions;
    }




}


