package co.com.virtualAsisIA.models;
// Generated 20/11/2015 04:16:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Caracterizacion generated by hbm2java
 */
@Entity
@Table(name="caracterizacion"
    ,schema="public"
)
public class Caracterizacion  implements java.io.Serializable {


     private int id;
     private String caracterizador;
     private Set clasificacionPreguntas = new HashSet(0);

    public Caracterizacion() {
    }

	
    public Caracterizacion(int id) {
        this.id = id;
    }
    public Caracterizacion(int id, String caracterizador, Set clasificacionPreguntas) {
       this.id = id;
       this.caracterizador = caracterizador;
       this.clasificacionPreguntas = clasificacionPreguntas;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="caracterizador", length=10)
    public String getCaracterizador() {
        return this.caracterizador;
    }
    
    public void setCaracterizador(String caracterizador) {
        this.caracterizador = caracterizador;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="caracterizacion")
    public Set getClasificacionPreguntas() {
        return this.clasificacionPreguntas;
    }
    
    public void setClasificacionPreguntas(Set clasificacionPreguntas) {
        this.clasificacionPreguntas = clasificacionPreguntas;
    }




}


