package co.com.virtualAsisIA.models;
// Generated 20/11/2015 04:16:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ClasificacionPregunta generated by hbm2java
 */
@Entity
@Table(name="clasificacion_pregunta"
    ,schema="public"
)
public class ClasificacionPregunta  implements java.io.Serializable {


     private int id;
     private Accion accion;
     private Caracterizacion caracterizacion;
     private TemaEspecifico temaEspecifico;
     private Set respuestas = new HashSet(0);

    public ClasificacionPregunta() {
    }

	
    public ClasificacionPregunta(int id) {
        this.id = id;
    }
    public ClasificacionPregunta(int id, Accion accion, Caracterizacion caracterizacion, TemaEspecifico temaEspecifico, Set respuestas) {
       this.id = id;
       this.accion = accion;
       this.caracterizacion = caracterizacion;
       this.temaEspecifico = temaEspecifico;
       this.respuestas = respuestas;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="accion_id")
    public Accion getAccion() {
        return this.accion;
    }
    
    public void setAccion(Accion accion) {
        this.accion = accion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="caract_id")
    public Caracterizacion getCaracterizacion() {
        return this.caracterizacion;
    }
    
    public void setCaracterizacion(Caracterizacion caracterizacion) {
        this.caracterizacion = caracterizacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tema_id")
    public TemaEspecifico getTemaEspecifico() {
        return this.temaEspecifico;
    }
    
    public void setTemaEspecifico(TemaEspecifico temaEspecifico) {
        this.temaEspecifico = temaEspecifico;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="clasificacionPregunta")
    public Set getRespuestas() {
        return this.respuestas;
    }
    
    public void setRespuestas(Set respuestas) {
        this.respuestas = respuestas;
    }




}


