package co.com.virtualAsisIA.models;
// Generated 20/11/2015 04:16:28 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Respuesta generated by hbm2java
 */
@Entity
@Table(name="respuesta"
    ,schema="public"
)
public class Respuesta  implements java.io.Serializable {


     private int id;
     private ClasificacionPregunta clasificacionPregunta;
     private String pregunta;
     private String respuesta;

    public Respuesta() {
    }

	
    public Respuesta(int id) {
        this.id = id;
    }
    public Respuesta(int id, ClasificacionPregunta clasificacionPregunta, String pregunta, String respuesta) {
       this.id = id;
       this.clasificacionPregunta = clasificacionPregunta;
       this.pregunta = pregunta;
       this.respuesta = respuesta;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cp_id")
    public ClasificacionPregunta getClasificacionPregunta() {
        return this.clasificacionPregunta;
    }
    
    public void setClasificacionPregunta(ClasificacionPregunta clasificacionPregunta) {
        this.clasificacionPregunta = clasificacionPregunta;
    }

    
    @Column(name="pregunta", length=200)
    public String getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(String pregunta) {
        this.pregunta = pregunta;
    }

    
    @Column(name="respuesta", length=1000)
    public String getRespuesta() {
        return this.respuesta;
    }
    
    public void setRespuesta(String respuesta) {
        this.respuesta = respuesta;
    }




}


