package co.com.virtualAsisIA.models;
// Generated 20/11/2015 04:16:28 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UnificacionAccion generated by hbm2java
 */
@Entity
@Table(name="unificacion_accion"
    ,schema="public"
)
public class UnificacionAccion  implements java.io.Serializable {


     private int id;
     private Accion accion;
     private String sinonimoAccion;

    public UnificacionAccion() {
    }

	
    public UnificacionAccion(int id) {
        this.id = id;
    }
    public UnificacionAccion(int id, Accion accion, String sinonimoAccion) {
       this.id = id;
       this.accion = accion;
       this.sinonimoAccion = sinonimoAccion;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="accion_id")
    public Accion getAccion() {
        return this.accion;
    }
    
    public void setAccion(Accion accion) {
        this.accion = accion;
    }

    
    @Column(name="sinonimo_accion", length=50)
    public String getSinonimoAccion() {
        return this.sinonimoAccion;
    }
    
    public void setSinonimoAccion(String sinonimoAccion) {
        this.sinonimoAccion = sinonimoAccion;
    }




}


